---
  - name: Download Zabbix Debian 9 (Stretch) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+stretch_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and ansible_distribution_major_version|int == 9

  - name: Download Zabbix Debian 8 (Jessie) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+jessie_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and ansible_distribution_major_version|int == 8
    
  - name: Download Zabbix Debian 7 (Wheezy) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+wheezy_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Debian" and ansible_distribution_major_version|int == 7
    
  - name: Download Zabbix Ubuntu 16 (Xenial) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+xenial_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 16

  - name: Download Zabbix Ubuntu 18 (Bionic) release deb file
    get_url:
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1%2Bbionic_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 18

  - name: Download Zabbix Ubuntu 14 (Trusty) release deb file
    get_url: 
      url="http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_agent_version }}-1+trusty_all.deb"
      dest="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 14

  - name: Apt install Zabbix release in Ubuntu/Debian
    apt: deb="/tmp/zabbix-release_{{ zabbix_agent_version }}-1.deb"
    when: ansible_os_family == "Debian"

  - name: Yum install Zabbix release in RHEL or CentOS
    yum: name=http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ zabbix_agent_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when: ansible_os_family == "RedHat"
    
  - name: Check or Install python apt installed on system
    apt:
      name: python-apt
      state: present

  - name: Apt install Zabbix agent
    apt:
      name: zabbix-agent
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Yum install Zabbix agent
    yum: name=zabbix-agent
    when: ansible_os_family == "RedHat"
